version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.9   # Next-gen CircleCI Docker image for Python 3.9
    steps:
      - checkout
      - run:
          name: Upgrade pip
          command: |
            python -m venv venv
            . venv/bin/activate
            python -m pip install --upgrade pip
      - run:
          name: Install dependencies
          command: |
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run Tests
          command: |
            . venv/bin/activate
            python manage.py test
