version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9   # Use the appropriate Python version
    steps:
      - checkout                    # Check out the code from your GitHub repo
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: Run Tests
          command: |
            . venv/bin/activate
            python manage.py test    # Run your Django tests

workflows:
  version: 2
  test:
    jobs:
      - build
